# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY main.py /app/main.py

# Install any needed packages specified in requirements.txt
RUN pip install langchain openai

# Run main.py when the container launches
CMD ["python", "main.py"]
